version: "3.3"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu-service

  menu-service:
    build: ./menu-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  user-service:
    build: ./user-service
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=${MONGODB_URI_USER_SERVICE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
